// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/LogTail.proto

package com.insightfinder.InsightFinderApp.protos;

public final class LogTailWrapper {
  private LogTailWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogTailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogTail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string projectName = 2;</code>
     * @return The projectName.
     */
    java.lang.String getProjectName();
    /**
     * <code>string projectName = 2;</code>
     * @return The bytes for projectName.
     */
    com.google.protobuf.ByteString
        getProjectNameBytes();

    /**
     * <code>string instanceName = 3;</code>
     * @return The instanceName.
     */
    java.lang.String getInstanceName();
    /**
     * <code>string instanceName = 3;</code>
     * @return The bytes for instanceName.
     */
    com.google.protobuf.ByteString
        getInstanceNameBytes();

    /**
     * <code>string keyword = 4;</code>
     * @return The keyword.
     */
    java.lang.String getKeyword();
    /**
     * <code>string keyword = 4;</code>
     * @return The bytes for keyword.
     */
    com.google.protobuf.ByteString
        getKeywordBytes();

    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     * an interger multiple of 10, unit is second
     * </pre>
     *
     * <code>int32 period = 6;</code>
     * @return The period.
     */
    int getPeriod();

    /**
     * <pre>
     *if client end init this taskId, send to backend, backend will check it if exist or not.
     *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
     * </pre>
     *
     * <code>string taskId = 7;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <pre>
     *if client end init this taskId, send to backend, backend will check it if exist or not.
     *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
     * </pre>
     *
     * <code>string taskId = 7;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();
  }
  /**
   * Protobuf type {@code LogTail}
   */
  public static final class LogTail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogTail)
      LogTailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogTail.newBuilder() to construct.
    private LogTail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogTail() {
      userName_ = "";
      projectName_ = "";
      instanceName_ = "";
      keyword_ = "";
      data_ = "";
      taskId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogTail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogTail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              projectName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              instanceName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              keyword_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 48: {

              period_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.internal_static_LogTail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.internal_static_LogTail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.class, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object projectName_;
    /**
     * <code>string projectName = 2;</code>
     * @return The projectName.
     */
    @java.lang.Override
    public java.lang.String getProjectName() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      }
    }
    /**
     * <code>string projectName = 2;</code>
     * @return The bytes for projectName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object instanceName_;
    /**
     * <code>string instanceName = 3;</code>
     * @return The instanceName.
     */
    @java.lang.Override
    public java.lang.String getInstanceName() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instanceName_ = s;
        return s;
      }
    }
    /**
     * <code>string instanceName = 3;</code>
     * @return The bytes for instanceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstanceNameBytes() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object keyword_;
    /**
     * <code>string keyword = 4;</code>
     * @return The keyword.
     */
    @java.lang.Override
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /**
     * <code>string keyword = 4;</code>
     * @return The bytes for keyword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERIOD_FIELD_NUMBER = 6;
    private int period_;
    /**
     * <pre>
     * an interger multiple of 10, unit is second
     * </pre>
     *
     * <code>int32 period = 6;</code>
     * @return The period.
     */
    @java.lang.Override
    public int getPeriod() {
      return period_;
    }

    public static final int TASKID_FIELD_NUMBER = 7;
    private volatile java.lang.Object taskId_;
    /**
     * <pre>
     *if client end init this taskId, send to backend, backend will check it if exist or not.
     *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
     * </pre>
     *
     * <code>string taskId = 7;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *if client end init this taskId, send to backend, backend will check it if exist or not.
     *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
     * </pre>
     *
     * <code>string taskId = 7;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectName_);
      }
      if (!getInstanceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, instanceName_);
      }
      if (!getKeywordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, keyword_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      if (period_ != 0) {
        output.writeInt32(6, period_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, taskId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectName_);
      }
      if (!getInstanceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, instanceName_);
      }
      if (!getKeywordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, keyword_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      if (period_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, period_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, taskId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail)) {
        return super.equals(obj);
      }
      com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail other = (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) obj;

      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getProjectName()
          .equals(other.getProjectName())) return false;
      if (!getInstanceName()
          .equals(other.getInstanceName())) return false;
      if (!getKeyword()
          .equals(other.getKeyword())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getPeriod()
          != other.getPeriod()) return false;
      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProjectName().hashCode();
      hash = (37 * hash) + INSTANCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceName().hashCode();
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + PERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getPeriod();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogTail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogTail)
        com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.internal_static_LogTail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.internal_static_LogTail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.class, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder.class);
      }

      // Construct using com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        projectName_ = "";

        instanceName_ = "";

        keyword_ = "";

        data_ = "";

        period_ = 0;

        taskId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.internal_static_LogTail_descriptor;
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getDefaultInstanceForType() {
        return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail build() {
        com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail buildPartial() {
        com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail result = new com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail(this);
        result.userName_ = userName_;
        result.projectName_ = projectName_;
        result.instanceName_ = instanceName_;
        result.keyword_ = keyword_;
        result.data_ = data_;
        result.period_ = period_;
        result.taskId_ = taskId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) {
          return mergeFrom((com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail other) {
        if (other == com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getProjectName().isEmpty()) {
          projectName_ = other.projectName_;
          onChanged();
        }
        if (!other.getInstanceName().isEmpty()) {
          instanceName_ = other.instanceName_;
          onChanged();
        }
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getPeriod() != 0) {
          setPeriod(other.getPeriod());
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 1;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 1;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object projectName_ = "";
      /**
       * <code>string projectName = 2;</code>
       * @return The projectName.
       */
      public java.lang.String getProjectName() {
        java.lang.Object ref = projectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          projectName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string projectName = 2;</code>
       * @return The bytes for projectName.
       */
      public com.google.protobuf.ByteString
          getProjectNameBytes() {
        java.lang.Object ref = projectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string projectName = 2;</code>
       * @param value The projectName to set.
       * @return This builder for chaining.
       */
      public Builder setProjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProjectName() {
        
        projectName_ = getDefaultInstance().getProjectName();
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 2;</code>
       * @param value The bytes for projectName to set.
       * @return This builder for chaining.
       */
      public Builder setProjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object instanceName_ = "";
      /**
       * <code>string instanceName = 3;</code>
       * @return The instanceName.
       */
      public java.lang.String getInstanceName() {
        java.lang.Object ref = instanceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instanceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instanceName = 3;</code>
       * @return The bytes for instanceName.
       */
      public com.google.protobuf.ByteString
          getInstanceNameBytes() {
        java.lang.Object ref = instanceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instanceName = 3;</code>
       * @param value The instanceName to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instanceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instanceName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstanceName() {
        
        instanceName_ = getDefaultInstance().getInstanceName();
        onChanged();
        return this;
      }
      /**
       * <code>string instanceName = 3;</code>
       * @param value The bytes for instanceName to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instanceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object keyword_ = "";
      /**
       * <code>string keyword = 4;</code>
       * @return The keyword.
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string keyword = 4;</code>
       * @return The bytes for keyword.
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string keyword = 4;</code>
       * @param value The keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string keyword = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyword() {
        
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /**
       * <code>string keyword = 4;</code>
       * @param value The bytes for keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private int period_ ;
      /**
       * <pre>
       * an interger multiple of 10, unit is second
       * </pre>
       *
       * <code>int32 period = 6;</code>
       * @return The period.
       */
      @java.lang.Override
      public int getPeriod() {
        return period_;
      }
      /**
       * <pre>
       * an interger multiple of 10, unit is second
       * </pre>
       *
       * <code>int32 period = 6;</code>
       * @param value The period to set.
       * @return This builder for chaining.
       */
      public Builder setPeriod(int value) {
        
        period_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * an interger multiple of 10, unit is second
       * </pre>
       *
       * <code>int32 period = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeriod() {
        
        period_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <pre>
       *if client end init this taskId, send to backend, backend will check it if exist or not.
       *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
       * </pre>
       *
       * <code>string taskId = 7;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *if client end init this taskId, send to backend, backend will check it if exist or not.
       *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
       * </pre>
       *
       * <code>string taskId = 7;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *if client end init this taskId, send to backend, backend will check it if exist or not.
       *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
       * </pre>
       *
       * <code>string taskId = 7;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *if client end init this taskId, send to backend, backend will check it if exist or not.
       *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
       * </pre>
       *
       * <code>string taskId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *if client end init this taskId, send to backend, backend will check it if exist or not.
       *if client end doesn't init it(give it a empty string value), backend will generate a uuid, then send it back with task data.
       * </pre>
       *
       * <code>string taskId = 7;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogTail)
    }

    // @@protoc_insertion_point(class_scope:LogTail)
    private static final com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail();
    }

    public static com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogTail>
        PARSER = new com.google.protobuf.AbstractParser<LogTail>() {
      @java.lang.Override
      public LogTail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogTail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogTail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogTail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogTail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogTail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/LogTail.proto\"\205\001\n\007LogTail\022\020\n\010us" +
      "erName\030\001 \001(\t\022\023\n\013projectName\030\002 \001(\t\022\024\n\014ins" +
      "tanceName\030\003 \001(\t\022\017\n\007keyword\030\004 \001(\t\022\014\n\004data" +
      "\030\005 \001(\t\022\016\n\006period\030\006 \001(\005\022\016\n\006taskId\030\007 \001(\tB;" +
      "\n)com.insightfinder.InsightFinderApp.pro" +
      "tosB\016LogTailWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LogTail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogTail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogTail_descriptor,
        new java.lang.String[] { "UserName", "ProjectName", "InstanceName", "Keyword", "Data", "Period", "TaskId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
