// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/Root.proto

package com.insightfinder.InsightFinderApp.protos;

public final class RootWrapper {
  private RootWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RootOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Root)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Ping ping = 1;</code>
     * @return Whether the ping field is set.
     */
    boolean hasPing();
    /**
     * <code>.Ping ping = 1;</code>
     * @return The ping.
     */
    com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping getPing();
    /**
     * <code>.Ping ping = 1;</code>
     */
    com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder getPingOrBuilder();

    /**
     * <code>.LogTail logTail = 2;</code>
     * @return Whether the logTail field is set.
     */
    boolean hasLogTail();
    /**
     * <code>.LogTail logTail = 2;</code>
     * @return The logTail.
     */
    com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getLogTail();
    /**
     * <code>.LogTail logTail = 2;</code>
     */
    com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder getLogTailOrBuilder();

    public com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.InnerMessageCase getInnerMessageCase();
  }
  /**
   * Protobuf type {@code protos.Root}
   */
  public static final class Root extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.Root)
      RootOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Root.newBuilder() to construct.
    private Root(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Root() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Root();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Root(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder subBuilder = null;
              if (innerMessageCase_ == 1) {
                subBuilder = ((com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_).toBuilder();
              }
              innerMessage_ =
                  input.readMessage(com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }
              innerMessageCase_ = 1;
              break;
            }
            case 18: {
              com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder subBuilder = null;
              if (innerMessageCase_ == 2) {
                subBuilder = ((com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_).toBuilder();
              }
              innerMessage_ =
                  input.readMessage(com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }
              innerMessageCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.insightfinder.InsightFinderApp.protos.RootWrapper.internal_static_protos_Root_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.insightfinder.InsightFinderApp.protos.RootWrapper.internal_static_protos_Root_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.class, com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.Builder.class);
    }

    private int innerMessageCase_ = 0;
    private java.lang.Object innerMessage_;
    public enum InnerMessageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PING(1),
      LOGTAIL(2),
      INNERMESSAGE_NOT_SET(0);
      private final int value;
      private InnerMessageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InnerMessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static InnerMessageCase forNumber(int value) {
        switch (value) {
          case 1: return PING;
          case 2: return LOGTAIL;
          case 0: return INNERMESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InnerMessageCase
    getInnerMessageCase() {
      return InnerMessageCase.forNumber(
          innerMessageCase_);
    }

    public static final int PING_FIELD_NUMBER = 1;
    /**
     * <code>.Ping ping = 1;</code>
     * @return Whether the ping field is set.
     */
    @java.lang.Override
    public boolean hasPing() {
      return innerMessageCase_ == 1;
    }
    /**
     * <code>.Ping ping = 1;</code>
     * @return The ping.
     */
    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping getPing() {
      if (innerMessageCase_ == 1) {
         return (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_;
      }
      return com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
    }
    /**
     * <code>.Ping ping = 1;</code>
     */
    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder getPingOrBuilder() {
      if (innerMessageCase_ == 1) {
         return (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_;
      }
      return com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
    }

    public static final int LOGTAIL_FIELD_NUMBER = 2;
    /**
     * <code>.LogTail logTail = 2;</code>
     * @return Whether the logTail field is set.
     */
    @java.lang.Override
    public boolean hasLogTail() {
      return innerMessageCase_ == 2;
    }
    /**
     * <code>.LogTail logTail = 2;</code>
     * @return The logTail.
     */
    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getLogTail() {
      if (innerMessageCase_ == 2) {
         return (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_;
      }
      return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
    }
    /**
     * <code>.LogTail logTail = 2;</code>
     */
    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder getLogTailOrBuilder() {
      if (innerMessageCase_ == 2) {
         return (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_;
      }
      return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (innerMessageCase_ == 1) {
        output.writeMessage(1, (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_);
      }
      if (innerMessageCase_ == 2) {
        output.writeMessage(2, (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (innerMessageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_);
      }
      if (innerMessageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.insightfinder.InsightFinderApp.protos.RootWrapper.Root)) {
        return super.equals(obj);
      }
      com.insightfinder.InsightFinderApp.protos.RootWrapper.Root other = (com.insightfinder.InsightFinderApp.protos.RootWrapper.Root) obj;

      if (!getInnerMessageCase().equals(other.getInnerMessageCase())) return false;
      switch (innerMessageCase_) {
        case 1:
          if (!getPing()
              .equals(other.getPing())) return false;
          break;
        case 2:
          if (!getLogTail()
              .equals(other.getLogTail())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (innerMessageCase_) {
        case 1:
          hash = (37 * hash) + PING_FIELD_NUMBER;
          hash = (53 * hash) + getPing().hashCode();
          break;
        case 2:
          hash = (37 * hash) + LOGTAIL_FIELD_NUMBER;
          hash = (53 * hash) + getLogTail().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.insightfinder.InsightFinderApp.protos.RootWrapper.Root prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Root}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Root)
        com.insightfinder.InsightFinderApp.protos.RootWrapper.RootOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.insightfinder.InsightFinderApp.protos.RootWrapper.internal_static_protos_Root_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.insightfinder.InsightFinderApp.protos.RootWrapper.internal_static_protos_Root_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.class, com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.Builder.class);
      }

      // Construct using com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        innerMessageCase_ = 0;
        innerMessage_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.insightfinder.InsightFinderApp.protos.RootWrapper.internal_static_protos_Root_descriptor;
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.RootWrapper.Root getDefaultInstanceForType() {
        return com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.getDefaultInstance();
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.RootWrapper.Root build() {
        com.insightfinder.InsightFinderApp.protos.RootWrapper.Root result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.RootWrapper.Root buildPartial() {
        com.insightfinder.InsightFinderApp.protos.RootWrapper.Root result = new com.insightfinder.InsightFinderApp.protos.RootWrapper.Root(this);
        if (innerMessageCase_ == 1) {
          if (pingBuilder_ == null) {
            result.innerMessage_ = innerMessage_;
          } else {
            result.innerMessage_ = pingBuilder_.build();
          }
        }
        if (innerMessageCase_ == 2) {
          if (logTailBuilder_ == null) {
            result.innerMessage_ = innerMessage_;
          } else {
            result.innerMessage_ = logTailBuilder_.build();
          }
        }
        result.innerMessageCase_ = innerMessageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.insightfinder.InsightFinderApp.protos.RootWrapper.Root) {
          return mergeFrom((com.insightfinder.InsightFinderApp.protos.RootWrapper.Root)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.insightfinder.InsightFinderApp.protos.RootWrapper.Root other) {
        if (other == com.insightfinder.InsightFinderApp.protos.RootWrapper.Root.getDefaultInstance()) return this;
        switch (other.getInnerMessageCase()) {
          case PING: {
            mergePing(other.getPing());
            break;
          }
          case LOGTAIL: {
            mergeLogTail(other.getLogTail());
            break;
          }
          case INNERMESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.insightfinder.InsightFinderApp.protos.RootWrapper.Root parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.insightfinder.InsightFinderApp.protos.RootWrapper.Root) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int innerMessageCase_ = 0;
      private java.lang.Object innerMessage_;
      public InnerMessageCase
          getInnerMessageCase() {
        return InnerMessageCase.forNumber(
            innerMessageCase_);
      }

      public Builder clearInnerMessage() {
        innerMessageCase_ = 0;
        innerMessage_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping, com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder, com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder> pingBuilder_;
      /**
       * <code>.Ping ping = 1;</code>
       * @return Whether the ping field is set.
       */
      @java.lang.Override
      public boolean hasPing() {
        return innerMessageCase_ == 1;
      }
      /**
       * <code>.Ping ping = 1;</code>
       * @return The ping.
       */
      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping getPing() {
        if (pingBuilder_ == null) {
          if (innerMessageCase_ == 1) {
            return (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_;
          }
          return com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
        } else {
          if (innerMessageCase_ == 1) {
            return pingBuilder_.getMessage();
          }
          return com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
        }
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      public Builder setPing(com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        innerMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      public Builder setPing(
          com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        innerMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      public Builder mergePing(com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping value) {
        if (pingBuilder_ == null) {
          if (innerMessageCase_ == 1 &&
              innerMessage_ != com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance()) {
            innerMessage_ = com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.newBuilder((com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          if (innerMessageCase_ == 1) {
            pingBuilder_.mergeFrom(value);
          }
          pingBuilder_.setMessage(value);
        }
        innerMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          if (innerMessageCase_ == 1) {
            innerMessageCase_ = 0;
            innerMessage_ = null;
            onChanged();
          }
        } else {
          if (innerMessageCase_ == 1) {
            innerMessageCase_ = 0;
            innerMessage_ = null;
          }
          pingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      public com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder getPingBuilder() {
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder getPingOrBuilder() {
        if ((innerMessageCase_ == 1) && (pingBuilder_ != null)) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          if (innerMessageCase_ == 1) {
            return (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_;
          }
          return com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
        }
      }
      /**
       * <code>.Ping ping = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping, com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder, com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          if (!(innerMessageCase_ == 1)) {
            innerMessage_ = com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.getDefaultInstance();
          }
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping, com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping.Builder, com.insightfinder.InsightFinderApp.protos.PingWrapper.PingOrBuilder>(
                  (com.insightfinder.InsightFinderApp.protos.PingWrapper.Ping) innerMessage_,
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        innerMessageCase_ = 1;
        onChanged();;
        return pingBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder> logTailBuilder_;
      /**
       * <code>.LogTail logTail = 2;</code>
       * @return Whether the logTail field is set.
       */
      @java.lang.Override
      public boolean hasLogTail() {
        return innerMessageCase_ == 2;
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       * @return The logTail.
       */
      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail getLogTail() {
        if (logTailBuilder_ == null) {
          if (innerMessageCase_ == 2) {
            return (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_;
          }
          return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
        } else {
          if (innerMessageCase_ == 2) {
            return logTailBuilder_.getMessage();
          }
          return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
        }
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      public Builder setLogTail(com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail value) {
        if (logTailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          logTailBuilder_.setMessage(value);
        }
        innerMessageCase_ = 2;
        return this;
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      public Builder setLogTail(
          com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder builderForValue) {
        if (logTailBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          logTailBuilder_.setMessage(builderForValue.build());
        }
        innerMessageCase_ = 2;
        return this;
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      public Builder mergeLogTail(com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail value) {
        if (logTailBuilder_ == null) {
          if (innerMessageCase_ == 2 &&
              innerMessage_ != com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance()) {
            innerMessage_ = com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.newBuilder((com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          if (innerMessageCase_ == 2) {
            logTailBuilder_.mergeFrom(value);
          }
          logTailBuilder_.setMessage(value);
        }
        innerMessageCase_ = 2;
        return this;
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      public Builder clearLogTail() {
        if (logTailBuilder_ == null) {
          if (innerMessageCase_ == 2) {
            innerMessageCase_ = 0;
            innerMessage_ = null;
            onChanged();
          }
        } else {
          if (innerMessageCase_ == 2) {
            innerMessageCase_ = 0;
            innerMessage_ = null;
          }
          logTailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder getLogTailBuilder() {
        return getLogTailFieldBuilder().getBuilder();
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      @java.lang.Override
      public com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder getLogTailOrBuilder() {
        if ((innerMessageCase_ == 2) && (logTailBuilder_ != null)) {
          return logTailBuilder_.getMessageOrBuilder();
        } else {
          if (innerMessageCase_ == 2) {
            return (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_;
          }
          return com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
        }
      }
      /**
       * <code>.LogTail logTail = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder> 
          getLogTailFieldBuilder() {
        if (logTailBuilder_ == null) {
          if (!(innerMessageCase_ == 2)) {
            innerMessage_ = com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.getDefaultInstance();
          }
          logTailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail.Builder, com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTailOrBuilder>(
                  (com.insightfinder.InsightFinderApp.protos.LogTailWrapper.LogTail) innerMessage_,
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        innerMessageCase_ = 2;
        onChanged();;
        return logTailBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.Root)
    }

    // @@protoc_insertion_point(class_scope:protos.Root)
    private static final com.insightfinder.InsightFinderApp.protos.RootWrapper.Root DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.insightfinder.InsightFinderApp.protos.RootWrapper.Root();
    }

    public static com.insightfinder.InsightFinderApp.protos.RootWrapper.Root getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Root>
        PARSER = new com.google.protobuf.AbstractParser<Root>() {
      @java.lang.Override
      public Root parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Root(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Root> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Root> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.insightfinder.InsightFinderApp.protos.RootWrapper.Root getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Root_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Root_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021protos/Root.proto\022\006protos\032\021protos/Ping" +
      ".proto\032\024protos/LogTail.proto\"K\n\004Root\022\025\n\004" +
      "ping\030\001 \001(\0132\005.PingH\000\022\033\n\007logTail\030\002 \001(\0132\010.L" +
      "ogTailH\000B\017\n\rinner_messageB8\n)com.insight" +
      "finder.InsightFinderApp.protosB\013RootWrap" +
      "perb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.insightfinder.InsightFinderApp.protos.PingWrapper.getDescriptor(),
          com.insightfinder.InsightFinderApp.protos.LogTailWrapper.getDescriptor(),
        });
    internal_static_protos_Root_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_Root_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Root_descriptor,
        new java.lang.String[] { "Ping", "LogTail", "InnerMessage", });
    com.insightfinder.InsightFinderApp.protos.PingWrapper.getDescriptor();
    com.insightfinder.InsightFinderApp.protos.LogTailWrapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
